# Generated by Django 3.2.5 on 2022-01-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images')),
                ('profile', models.FileField(upload_to='files')),
            ],
        ),
    ]
