# Generated by Django 3.2.5 on 2022-02-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('pdfname', models.CharField(max_length=200)),
                ('pdffile', models.FileField(upload_to='files')),
            ],
        ),
    ]
