# Generated by Django 3.2.5 on 2022-02-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='pdfname',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='pdffile',
            new_name='File',
        ),
    ]
