# Generated by Django 3.2.5 on 2022-02-11 09:47

from pickle import TRUE
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220210_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID'),
        ),
    ]
