# Generated by Django 3.2.5 on 2022-02-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_pdf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='Pdf_no',
            field=models.IntegerField(default=1),
        ),
    ]
