# Generated by Django 3.2.5 on 2022-02-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pdf_pdf_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='id',
        ),
        migrations.AlterField(
            model_name='pdf',
            name='Pdf_no',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
