# Generated by Django 3.2.5 on 2022-02-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220218_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='Pdf_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
