# Generated by Django 3.2.5 on 2022-02-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_pdf_pdf_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='Pdf_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
