# Generated by Django 3.2.5 on 2022-02-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_pdf_pdf_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='Pdf_no',
            new_name='No',
        ),
    ]
