# Generated by Django 3.2.5 on 2022-02-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_pdf_no_pdf_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='File',
            field=models.FileField(upload_to=''),
        ),
    ]
