# Generated by Django 3.2.5 on 2022-02-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('Sr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Book_name', models.CharField(max_length=60)),
                ('Publication', models.CharField(max_length=60)),
                ('Semester', models.IntegerField(max_length=1)),
                ('Edition', models.IntegerField(max_length=4)),
            ],
        ),
    ]
