# Generated by Django 3.2.5 on 2022-02-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='Edition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='Semester',
            field=models.IntegerField(),
        ),
    ]
