# Generated by Django 3.2.5 on 2022-02-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220225_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Book_no',
        ),
    ]
