# Generated by Django 3.2.5 on 2022-02-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
