# Generated by Django 3.2.5 on 2022-02-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_id',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
