# Generated by Django 3.2.5 on 2022-02-27 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_book_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Book_id',
        ),
    ]
