# Generated by Django 3.2.5 on 2022-03-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_book_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Edition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
