# Generated by Django 3.2.5 on 2022-03-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_book_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Edition',
            field=models.CharField(max_length=4),
        ),
    ]
