# Generated by Django 3.2.5 on 2022-03-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_book_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='id',
        ),
        migrations.AlterField(
            model_name='images',
            name='id_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
